Be careful when referencing defines and do not redeclare built-ins (C++)
__STDC_VERSION__ is not mandatory for g++ to define, and when compiling
the generated code with -Werror=undef this yields

    error: "__STDC_VERSION__" is not defined, evaluates to 0

C++ has built-in support for bool, so make sure this is only defined
when __cplusplus is not set. Use cstdint for uintXX_t values.